# Generated by Django 3.2 on 2026-04-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('is_under_represented', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact E-mail')),
                ('webpage', models.URLField(blank=True)),
                ('institution', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, choices=[('PhD student', 'PhD student'), ('Medical Doctor', 'Medical Doctor'), ('Post-doctoral researcher', 'Post-doctoral researcher'), ('Senior researcher/ scientist', 'Senior researcher/ scientist'), ('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Group leader/ Director/ Head of Department', 'Group leader/ Director/ Head of Department')], max_length=50)),
                ('grad_month', models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, verbose_name='Month')),
                ('grad_year', models.CharField(blank=True, max_length=4, verbose_name='Year')),
                ('brain_structure', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('N', 'Neuron'), ('L', 'Layer'), ('C', 'Column'), ('R', 'Region'), ('W', 'Whole Brain')], max_length=9)),
                ('modalities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EP', 'Electrophysiology (EEG, MEG, ECoG)'), ('OE', 'Other electrophysiology'), ('MR', 'MRI'), ('PE', 'PET'), ('DT', 'DTI'), ('BH', 'Behavioural'), ('ET', 'Eye Tracking'), ('BS', 'Brain Stimulation'), ('GT', 'Genetics'), ('FN', 'fNIRS'), ('LE', 'Lesions and Inactivations')], max_length=32)),
                ('methods', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UV', 'Univariate'), ('MV', 'Multivariate'), ('PM', 'Predictive Models'), ('DC', 'DCM'), ('CT', 'Connectivity'), ('CM', 'Computational Modeling'), ('AM', 'Animal Models')], max_length=20)),
                ('domains', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CG', 'Cognition (general)'), ('MM', 'Memory'), ('SS', 'Sensory systems'), ('MO', 'Motor Systems'), ('LG', 'Language'), ('EM', 'Emotion'), ('PN', 'Pain'), ('LE', 'Learning'), ('AT', 'Attention'), ('DE', 'Decision Making'), ('DV', 'Developmental'), ('SL', 'Sleep'), ('CN', 'Consciousness'), ('CL', 'Clinical (general)'), ('DM', 'Dementia'), ('PK', 'Parkinson'), ('DD', 'Other degenerative diseases'), ('PS', 'Psychiatry'), ('AD', 'Addiction'), ('ON', 'Oncology'), ('EV', 'Evolutionary'), ('CM', 'Cellular and Molecular'), ('BI', 'Bioinformatics'), ('NC', 'Neuropharmacology'), ('ET', 'Ethics')], max_length=74)),
                ('keywords', models.CharField(blank=True, max_length=250)),
                ('orcid', models.CharField(blank=True, help_text='Please insert the information from the brackets: https://orcid.org/[ID]', max_length=30, null=True, verbose_name='ORCID')),
                ('twitter', models.CharField(blank=True, help_text='Please insert the information from the brackets: https://twitter.com/[username]', max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='Please insert the information from the brackets: https://linkedin.com/in/[username]', max_length=200, null=True, verbose_name='LinkedIn')),
                ('github', models.CharField(blank=True, help_text='Please insert the information from the brackets: https://github.com/[username]', max_length=200, null=True, verbose_name='GitHub')),
                ('google_scholar', models.CharField(blank=True, help_text='Please insert the information from the brackets: https://scholar.google.com/citations?user=[ID]', max_length=200, null=True, verbose_name='Google Scholar')),
                ('researchgate', models.CharField(blank=True, help_text='Please insert the information from the brackets: https://www.researchgate.net/profile/[username]', max_length=200, null=True, verbose_name='ResearchGate')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_claims', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'institution', 'updated_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('reviewer_position', models.CharField(blank=True, choices=[('PhD student', 'PhD student'), ('Medical Doctor', 'Medical Doctor'), ('Post-doctoral researcher', 'Post-doctoral researcher'), ('Senior researcher/ scientist', 'Senior researcher/ scientist'), ('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Group leader/ Director/ Head of Department', 'Group leader/ Director/ Head of Department')], max_length=50)),
                ('reviewer_institution', models.CharField(max_length=100)),
                ('seen_at_conf', models.BooleanField(null=True)),
                ('comment', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.profile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', profiles.models.EnumField(choices=[('JP', 'Journal Paper'), ('RE', 'Report'), ('PP', 'Preprint'), ('BO', 'Book'), ('BP', 'Blog Post'), ('NE', 'News/Magazine')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField(help_text='First Middle Last → Last, F. M.<br>One author per line.')),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateField()),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('doi', models.CharField(blank=True, max_length=200, null=True, verbose_name='DOI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
